#!/usr/bin/env bash

set -Eeuo pipefail

if [[ $# -ne 1 ]]; then
    echo "usage: ./driver.sh <path/to/file.cpp>"
    exit 1
fi

IN="$1"

# dirname + filename pieces
DIR="$(dirname "$IN")"
BASE="$(basename "$IN")"
NAME="${BASE%.cpp}"

OUT="${DIR}/${NAME}_inst.cpp"

python3 value_profile/add_logs.py "$IN" "$OUT"

mkdir -p build
mkdir -p logs

# compile
g++ -std=c++23 -g "$OUT" -o "build/${NAME}"

echo "generated: $OUT"
echo "binary:    build/${NAME}"

# run program and collect values
g++ -std=c++23 -g "$OUT"

./a.out >/dev/null

rm a.out

echo "generated profile data"

./value_profile/parse_logs.py logs/${BASE}.txt

echo "parsed profile data"

cp logs/${BASE}.txt profile_stats.txt
